# git-sumi ~ configuration file
# Config: https://sumi.rs/docs/configuration
# Rules: https://sumi.rs/docs/rules

# Displays parsed commit message.
display = true

# Sets display format: cli, json, table, toml.
# See https://sumi.rs/docs/configuration#format
format = "cli"

# Rule: Description must start with the specified case.
# Options: 'any', 'lower', 'upper'.
description_case = "lower"

# Rule: Use the imperative mood in the description.
# Example: 'Fix bug' instead of 'Fixed bug'.
imperative = true

# Rule: Do not end commit header with a period.
no_period = true

# Rule: Header length limit.
# A value of 0 disables the rule.
max_header_length = 50

# Rule: Body line length limit.
# A value of 0 disables the rule.
max_body_length = 72

# Rule: Follow Conventional Commits format.
# See https://www.conventionalcommits.org/.
conventional = true

# Rule: List of allowed commit types.
# An empty list allows all types. Example: ["feat", "fix", "docs"].
types_allowed = [
    "fix",
    "feat",
    "build",
    "chore",
    "ci",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
]
